# Generated by Django 4.0.4 on 2022-06-24 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_courscategory_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courscategory',
            name='featured_img',
            field=models.ImageField(null=True, upload_to='course_imgs/'),
        ),
        migrations.AddField(
            model_name='courscategory',
            name='techs',
            field=models.TextField(null=True),
        ),
    ]
