# Generated by Django 4.0.4 on 2022-06-24 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_courscategory_featured_img_courscategory_techs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courscategory',
            name='featured_img',
        ),
        migrations.RemoveField(
            model_name='courscategory',
            name='techs',
        ),
        migrations.AddField(
            model_name='course',
            name='featured_img',
            field=models.ImageField(null=True, upload_to='course_imgs/'),
        ),
        migrations.AddField(
            model_name='course',
            name='techs',
            field=models.TextField(null=True),
        ),
    ]
