# Generated by Django 4.0.4 on 2022-08-16 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_teacher_detail_alter_chapter_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='mobile_no',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='student',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='student',
            name='qualification',
        ),
    ]
