# Generated by Django 4.0.4 on 2022-09-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_courseassignement_studentassignement'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassignement',
            name='student_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
