# Generated by Django 4.0.4 on 2022-09-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name_plural': '9. Notification'},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notif_text',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_for',
            field=models.CharField(max_length=200, verbose_name='Notification for'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_read_status',
            field=models.BooleanField(default=False, verbose_name='Notification Status'),
        ),
    ]
