# Generated by Django 4.0.4 on 2022-09-20 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_quiz_quizquestion_coursequiz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizquestion',
            old_name='questions',
            new_name='question',
        ),
    ]
