# Generated by Django 4.0.4 on 2022-09-24 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_coursequiz_options_coursequiz_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursequiz',
            options={'verbose_name_plural': '13. Attempted Quiz'},
        ),
        migrations.RemoveField(
            model_name='coursequiz',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursequiz',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='coursequiz',
            name='teacher',
        ),
        migrations.AddField(
            model_name='coursequiz',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.quizquestion'),
        ),
        migrations.AddField(
            model_name='coursequiz',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.student'),
        ),
    ]
