# Generated by Django 4.0.4 on 2022-09-24 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_coursequiz_options_remove_coursequiz_question_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AttempQuiz',
            new_name='AttemptQuiz',
        ),
    ]
