# Generated by Django 4.0.4 on 2022-10-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_course_course_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '16. FaQ',
            },
        ),
        migrations.AlterModelOptions(
            name='studymaterial',
            options={'verbose_name_plural': '15.Course Study Materials'},
        ),
    ]
