# Generated by Django 4.0.4 on 2022-10-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_student_login_via_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='login_via_otp',
            field=models.BooleanField(default=False),
        ),
    ]
